---
title: Silego（シレゴ）社**SLG46826**試してみたレポート
abstract: FPGAっぽいPSoC(R)っぽいおもしろ石でＬチカする
circle: KY技研
author: "@_K4ZUKI_"
comiket: 技術書典5（予定）
year: 2018
publisher: 印刷会社で印刷製本
docrevision: "1.0"
front: "images/computer-lsi.png"
verbcolored: false
# rmnote: false
...
